### ISSUE TITLE
No -U option to auto update to the latest version

### ISSUE THREAD

**Issue by javier-lopez** [rjw57/yt#19]
Just as youtube-dl I think it could be a great idea if yt could autoupdate itself once installed

**Comment by rjw57** [comment]
Hmm... I think it'd be better if I pulled my finger out and updated pypi more often. Then one can update via pip/easy_install.

**Comment by javier-lopez** [comment]
Hi Rich,

Thanks for answering, I was thinking on this option because I plan to package this program for debian|ubuntu, however once it gets packaged there will be paperwork to do in order to update it, an option to auto update would be a great workaround for people who cannot wait. By the way, I've not found any license in yt, is it public?, best regards

**Comment by rjw57** [comment]
Ah yes. My bad. Added in 6e57773. Assuming that the Debian packaging is non-surprising, wouldn't yt then be installed in the system Python directory? Then you'd need to run with `-U` as root and, further, it would change files behind the package manager's back. I suspect both of those are non-ideal for Debian. In any case, I'm not sure how one would implement `-U` without simply calling into pip/easy_install. (Which should be the correct thing to do assuming I keep on top of #21.)

For the moment, I'm closing this as a WONTFIX. Pull-requests implementing the option are welcome, but they'll have to be clean.
