### ISSUE TITLE
.

### ISSUE THREAD

**Issue by imu1254** [rjw57/yt#30]

**Comment by rjw57** [comment]
Hi, @imu1254. To be honest, yt as it stands needs a bit re-factor to support user logins properly. Adding in support for playlists would require adding support for logging in first which, probably, means yt needs to be separated out a bit from the hack it currently is. I've got it as a long term back-of-mind goal but I've not really got any good ideas on how to do it.

**Comment by rjw57** [comment]
Oh, I see. I thought you meant a user's own personal playlists. I'd add playlist support directly into yt if I were you. Just call oxmplayer once for every video.
