### ISSUE TITLE
Option to pick resolution

### ISSUE THREAD

**Issue by parkerlreed** [rjw57/yt#5]
It seems that youtube-dl always plays the highest quality version of a chosen video. When 1080p is available this is fine on my home network, but my school's wifi network does not have enough bandwidth to handle the 1080p stream. I was looking at the arguments for youtube-dl to see if there was anything to maybe play a lower quality version of a video. Didn't see anything very apparent. Not sure whether this is an issue with youtube-dl or something that could be implemented in yt. If the lower quality can be played with youtube-dl a great feature for yt wold be to have an extra diiaog for quality selection or maybe an arguemnt to set the max video quality that is played.

**Comment by hololight** [comment]
If you are looking for audio only, the patch I submitted (and were commited the other day) allow for a 'no video' command line switch. This also results the 'yt' requesting the lowest possible quality versions so as to save on bandwidth.

My next addition is going to be something along the lines of what you are looking for, eg... --low-quality, --med-quality, etc.

**Comment by hololight** [comment]
There is now a command line argument to specify a low bandwidth video preference. Once you update, check out the help.

**Comment by parkerlreed** [comment]
Thank you so much. That works better than I could have ever hoped for.
